### ISSUE TITLE
Training do not work. class MyDataset broken

### ISSUE THREAD

**Issue by Vadim2S** [iiscleap/ZEST#1]
class MyDataset broken

1) folder parameter and therefore train/valid/test files do not used at all
2) wav_files and speaker_features are same .npy files
3) __getitem__ can not find "self.wav_files[audio_ind].replace(".wav", ".npy")"

i presume there must be something like this

wav_files = os.listdir(folder)
wav_files = [x for x in wav_files if ".wav" in x]

instead this

wav_files = os.listdir(speaker_folder)
wav_files = [x for x in wav_files if ".npy" in x]

**Comment by Soumya-dutta** [comment]
Did you extract the EASE embeddings before running this code?

**Comment by Vadim2S** [comment]
:-) This error resides in speaker_classifier.py file what used for extracting EASY embeddings :-) 

class MyDataset in pitch_attention_adv.py has right code:

wav_files = os.listdir(folder)
wav_files = [x for x in wav_files if ".wav" in x]

**Comment by Soumya-dutta** [comment]
I would request to follow the steps written in the main README file. Once you get the x-vectors you will have .npy files in the speaker folder. You will require the speaker labels and the emotion labels for the speaker classifier.

**Comment by Vadim2S** [comment]
Hmm... Are you say 'folder' and 'target_folder' in get_speaker_embedding.py code **must** point to **same** folder?

I am create .npy files in separate folder from .wav i.e

```
classifier = EncoderClassifier.from_hparams(source="speechbrain/spkrec-ecapa-voxceleb", run_opts={"device":"cuda"})
folder = r"ZEST\_ESD\"
target_folder = r"ZEST\_ESD\x-vectors"
os.makedirs(target_folder, exist_ok=True)
wav_files = os.listdir(folder)
wav_files = [x for x in wav_files if ".wav" in x]
wav_files = [x for x in wav_files if ".npy" not in x]
```

What right file structure?

Something like this?

ESD
...train
......0011_000341.wav
......0011_000341.npy
...val
...test
