### ISSUE TITLE
RuntimeError: "nll_loss_forward_no_reduce_cuda_kernel_index" not implemented for 'Int' in pitch_attention_adv.py 

### ISSUE THREAD

**Issue by Vadim2S** [iiscleap/ZEST#3]
Error in  "pitch_attention_adv.py", line 338

"loss3 = nn.CrossEntropyLoss(reduction='none')(spkr_out, speaker_label).sum()"

  File "........\venv\lib\site-packages\torch\nn\functional.py", line 3053, in cross_entropy
    return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
RuntimeError: "nll_loss_forward_no_reduce_cuda_kernel_index" not implemented for 'Int'

I presume the must be 

"loss3 = nn.CrossEntropyLoss(reduction='none')(spkr_out, speaker_label.long()).sum()"

or something like this

**Comment by Soumya-dutta** [comment]
Please let me know if .long() is required for correctly running in your case. For me the provided code runs without any error.

**Comment by Vadim2S** [comment]
Some things like using outdated and deprecated pickle5 say me what you may use really old Python and PyTorch version. What version you use? Here may be major difference.

**Comment by Soumya-dutta** [comment]
I am using Pytorch 1.13.1 and Python 3.9.13

**Comment by Vadim2S** [comment]
Please check again. This is just imposible. You code contains pickle5. For example 

pitch_attention_adv.py, line 19 and speaker_classifier.py line 15 has code

``
import pickle5 as pickle
``

but pickle5 can not be installed at Python 3.9. PIP page [https://pypi.org/project/pickle5/](url) says:

"This package backports all features and APIs added in the pickle module in Python 3.8.3, including the [PEP 574](https://www.python.org/dev/peps/pep-0574/) additions. It should work with Python 3.5, 3.6 and 3.7."

Python >=3.5, <3.8 

![изображение](https://github.com/iiscleap/ZEST/assets/84853762/b3d345ff-98e8-400c-8349-91eb8e5bf6fc)

same for Conda. There no pickle5 package for Python > 3.7

![изображение](https://github.com/iiscleap/ZEST/assets/84853762/6a9d05b4-2167-46a6-8170-7060b91009b6)

an if you try install it from source even at clear Python 3.9 virtual environment you get error "PyPickleBuffer_GetBuffer already defined" (for Python 3.6 all OK)

**Comment by Soumya-dutta** [comment]
Please try installing pickle5 by installing pip install pickle5. I am not aware of this problem in Python 3.9. I have been using pickle5 for a long time. It has never given me any problem.
