### ISSUE TITLE
RuntimeError: Serialization of parametrized modules is only supported through state_dict() in pitch_attention_adv.py

### ISSUE THREAD

**Issue by Vadim2S** [iiscleap/ZEST#4]
In line 381 here code 

torch.save(model, 'f0_predictor.pth')

Due PyTorch documentation this approach are wrong. There must be code similar to 

torch.save(model.state_dict(), PATH)

or 

torch.save({
            'epoch': epoch,
            'model_state_dict': model.state_dict(),
            'optimizer_state_dict': optimizer.state_dict(),
            'loss': loss,
            ...
            }, PATH)

See [https://pytorch.org/tutorials/beginner/saving_loading_models.html#saving-loading-a-general-checkpoint-for-inference-and-or-resuming-training](url)

P.S. I train model whole night, get error at save stage and lost all progress :-(

**Comment by Soumya-dutta** [comment]
I am not sure why this issue has come up in your case. While storing models as .state_dict is the recommended approach, the method used in the code should not break unless you change some class names and method names.

**Comment by wosyoo** [comment]
I have the same problem,have you solved it?
