### ISSUE TITLE
How to obtain the `esd_f0_stats.pth` file required to train the HiFi-GAN?

### ISSUE THREAD

**Issue by jishnub** [iiscleap/ZEST#5]
Is this something that is created from the database? I tried following the steps, but this file seems to be missing. Any help is appreciated!

**Comment by iiscleap** [comment]
Thanks for using this code.

Sorry for the oversight. This is actually not used in the code, but used in the original speech resynthesis paper. I have uploaded this file in the repo. Let me know if this works now.

**Comment by jishnub** [comment]
Thank you, the training works now with this file present. If this is not used in the code, would it also be fine to comment out the line:
https://github.com/iiscleap/ZEST/blob/a018911ca4dcd9841a378a7cf0708628bfd661ae/code/HiFi-GAN/train.py#L95
This is where the file seems to be loaded (similarly, for validation).

Also, how is this file generated?

**Comment by Soumya-dutta** [comment]
Yes..you can comment out that line. This file  had a speaker wise mean and variance stored. Since, ZEST does not use speaker wise mean-variance normalization, this file is not used anymore.
